### PR TITLE
Implement faster JSON (un)marshaling via jsoniter pkg

### PR DESCRIPTION
**Pull request by VojtechVitek**
```
webrpc-gen -schema=proto.ridl -target=golang -client -json=jsoniter -out=client.gen.go
```

Fixes https://github.com/webrpc/webrpc/issues/20

Good read: https://www.cockroachlabs.com/blog/high-performance-json-parsing/

### CODE REVIEW

**Comment by VojtechVitek** [comment]
Merging as an experimental feature.

Passed my initial testing against WebRPC interoperability test: https://github.com/webrpc/webrpc/tree/master/tests.

**Comment by VojtechVitek** [comment]
Released in golang@0.12.0

**Comment by pkieltyka** [comment]
Very nice!!!

**Comment by pkieltyka** [comment]
I wonder if ffjson is an option for us? Code gen could mean better performance, and also no dependency when using the generated code. Something to experiment with in future potentially

**Comment by VojtechVitek** [comment]
@pkieltyka I believe code gen based [ffjson](https://github.com/pquerna/ffjson) or [easyjson](https://github.com/mailru/easyjson) could be options too. However, we'd have to spit out `//go:generate` code for the end-users, since we're constrained by printing out text only from the Go templates. Or we'd have to spit out the optimized generated code from the templates somehow.

btw `jsoniter` is doing really well in performance comparisons.. hard to tell if ffjson/easyjson are really better options.

**Comment by pkieltyka** [comment]
Neat. Yea wouldn’t want to spit on go:generate in the code. My hope is it would output static code. The protobuf tools for optimization pb marshalling can output static optimized marshallers, but I guess ffjson and easyjson don’t do that On Jul 20, 2023, at 6:55 PM, Vojtech Vitek (golang.cz) ***@***.***> wrote:﻿
@pkieltyka I believe code gen based ffjson or easyjson could be options too. However, we'd have to spit out //go:generate code for the end-users, since we're constrained by printing out text only from the Go templates. Or we'd have to spit out the optimized generated code from the templates somehow.
btw jsoniter is doing really well in performance comparisons.. hard to tell if ffjson/easyjson are really better options.

**Comment by VojtechVitek** [comment]
Both ffjson and easyjson generated code still imports some packages:

Screen Shot 2023-07-21 at 1 09 35 AM

Screen Shot 2023-07-21 at 1 10 22 AM

**Comment by pkieltyka** [comment]
ah ya.. not useful then. Thanks for checking 🙏🙏

**Pull request merged**
